### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by tf** [sr3d/GithubFinder#10]
Whenever I open more than three columns, the layout breaks:

http://twitpic.com/2li2zq

This is coursed by a "height" css property that is set on the div.ico elements. Occurs in FF 3.6 and Chrome 5.0

**Comment by sr3d** [comment]
thanks for the bug report.  I was busy the past few days but I'll fix it tomorrow.

**Comment by sr3d** [comment]
issue has been fixed

**Comment by tf** [comment]
Thanks. Works great now!
