### ISSUE TITLE
default to master branch

### ISSUE THREAD

**Issue by paulirish** [sr3d/GithubFinder#3]
it shouldnt start in gh-pages or wherever but always default to master if possible

**Comment by sr3d** [comment]
The app already starts in master branch by default.  The app also detects the document.referrer to grab the user/repo/branch data, so you were probably visiting a gh-pages branch before coming to GHFinder.

**Comment by paulirish** [comment]
alright sounds like you want that too.  :)
if i can spot any weird behavior i'll holler. 
closing
