### ISSUE TITLE
Doesnt seem to work in Chrome on Mac

### ISSUE THREAD

**Issue by jacquescrocker** [sr3d/GithubFinder#4]
Very cool app! However there seems to be an issue in OSX Chrome. Clicking on the items in the first column don't do anything: http://cl.ly/9d302f6e1449e27a7a9b

**Comment by sr3d** [comment]
I'm using Chrome for testing as well and so far it's working for me.  Can you take a look at the console (Alt Cmd I), and let me know if you see any any error?

Thanks!

**Comment by jacquescrocker** [comment]
Ah, good suggestion. It is throwing a bunch of errors:
http://cl.ly/7f02e2a61b14f65b972b

I cleared cache and everything and it still shows the error. LEt me know if you need any more help in tracking this down.

**Comment by jacquescrocker** [comment]
Oh, i see the problem. http://codeshelver.com/ conflicts with it. Disabling that chrome extension fixes things.

jQuery and Prototype... why oh why can't you two get along? :-)
